name: Run extra tests
on:
  pull_request:
    paths:
      - 3-extra/**
jobs:
  extra-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run extra tests
      run: npm test -- --selectProjects extra
